### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by pitothepowerof3** [sibartlett/atom-clippy#2]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (C:\Users\Tristen\AppData\Local\atom\app-0.188.0\resources\app\src\atom.js:54:11)
Object.activate (C:\Users\Tristen\.atom\packages\clippy\lib\index.coffee:98:9)
```

**Comment by sibartlett** [comment]
@pitothepowerof3 thanks for opening this issue, I've published a new version of this package.
